Repository Tandain-Group/Tandain-Apps, pull requests merged in 2025-02, with the labels that each got.

#2 Add gitignore .idea
  .gitignore
Labels: refactor

#3 Commit idea files
  .idea/gradle.xml
  .idea/misc.xml
  .idea/other.xml
Labels: refactor

#4 Add splashscreen
  .idea/gradle.xml
  .idea/vcs.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/tandain/tandainapps/MainActivity.kt
  app/src/main/res/values/themes.xml
  buildLogic/src/main/java/com/tandain/tandainapps/buildlogic/utils/Modules.kt
  common/src/main/AndroidManifest.xml
  core/resources/src/main/res/values/colors.xml
  core/resources/src/main/res/values/dimens.xml
  features/splashscreen/.gitignore
  features/splashscreen/build.gradle.kts
  features/splashscreen/consumer-rules.pro
  features/splashscreen/proguard-rules.pro
  features/splashscreen/src/main/AndroidManifest.xml
  features/splashscreen/src/main/res/drawable/ic_logo_splashscreen.xml
  features/splashscreen/src/main/res/drawable/resized_ic_splashscreen.xml
  features/splashscreen/src/test/java/com/tandain/tandainapps/splashscreen/ExampleUnitTest.kt
  settings.gradle.kts
  utils/.gitignore
  utils/build.gradle.kts
  utils/consumer-rules.pro
  utils/proguard-rules.pro
  utils/src/androidTest/java/com/tandain/tandainapps/common/ExampleInstrumentedTest.kt
  utils/src/main/AndroidManifest.xml
  utils/src/test/java/com/tandain/tandainapps/common/ExampleUnitTest.kt
Labels: feature

#5 Create LICENSE
  LICENSE
Labels: documentation
