Repository Tandain-Group/Tandain-Apps, pull requests merged in 2025-03, with the labels that each got.

#8 [TDN-6][Refactor] - Refactoring navigation into view model using navigator
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/tandain/tandainapps/TandainApplication.kt
  app/src/main/java/com/tandain/tandainapps/di/AppModule.kt
  app/src/main/java/com/tandain/tandainapps/initilizer/CommonInitializer.kt
  app/src/main/java/com/tandain/tandainapps/initilizer/KoinInitializer.kt
  app/src/main/java/com/tandain/tandainapps/navigation/TandainNavHost.kt
  buildLogic/src/main/java/com/tandain/tandainapps/buildlogic/plugins/TandainFeaturePlugin.kt
  core/navigation/build.gradle.kts
  core/navigation/src/main/java/com/tandain/tandainapps/navigation/ext/NavigationExtension.kt
  core/navigation/src/main/java/com/tandain/tandainapps/navigation/impl/NavigatorImpl.kt
  core/navigation/src/main/java/com/tandain/tandainapps/navigation/interfaces/NavigationAction.kt
  core/navigation/src/main/java/com/tandain/tandainapps/navigation/interfaces/Navigator.kt
  core/navigation/src/main/java/com/tandain/tandainapps/navigation/route/BottomNavDestinations.kt
  core/navigation/src/main/java/com/tandain/tandainapps/navigation/route/Destination.kt
  core/navigation/src/main/java/com/tandain/tandainapps/navigation/route/PreLoginDestinations.kt
  core/navigation/src/main/java/com/tandain/tandainapps/navigation/route/TandainRoutes.kt
  core/navigation/src/main/java/com/tandain/tandainapps/navigation/utils/DeepLinkConstant.kt
  core/navigation/src/main/java/com/tandain/tandainapps/navigation/utils/NavHelper.kt
  features/home/src/main/java/com/tandain/tandainapps/home/di/HomeModule.kt
  features/home/src/main/java/com/tandain/tandainapps/home/model/HomeUiEvent.kt
  features/home/src/main/java/com/tandain/tandainapps/home/navigation/HomeNavigation.kt
  features/home/src/main/java/com/tandain/tandainapps/home/presentation/HomeScreen.kt
  features/home/src/main/java/com/tandain/tandainapps/home/presentation/HomeViewModel.kt
  gradle/libs.versions.toml
Labels: refactor

#9 Add PR template and downgrade AGP version
  .github/pull_request_template.md
  README.md
  gradle/libs.versions.toml
Labels: documentation

#12 TDN-8 setup base view model
  core/component/src/main/java/com/tandain/tandainapps/component/base/BaseViewModel.kt
  core/component/src/main/java/com/tandain/tandainapps/component/base/viewmodel/BaseViewModel.kt
  core/component/src/main/java/com/tandain/tandainapps/component/base/viewmodel/TimeCapsule.kt
  features/home/src/main/java/com/tandain/tandainapps/home/presentation/HomeScreen.kt
  features/home/src/main/java/com/tandain/tandainapps/home/presentation/HomeViewModel.kt
  features/home/src/main/java/com/tandain/tandainapps/home/presentation/SplashScreen.kt
  features/home/src/main/java/com/tandain/tandainapps/home/presentation/dummy/HomeEffect.kt
  features/home/src/main/java/com/tandain/tandainapps/home/presentation/dummy/HomeEvent.kt
  features/home/src/main/java/com/tandain/tandainapps/home/presentation/dummy/HomeState.kt
Labels: improvement, refactor
